config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  
  def self.search_result(category,author,title,description,feedback)
	articles = Article.all
    articles = articles.where(category: category) if category!= "Category" 
    articles = articles.where(author: author) if author!= "Author" 
    articles = articles.where(["title LIKE ?","%#{title}%"]) if title.present? 
    articles = articles.where(["description LIKE ?","%#{description}%"]) if description.present? 
    articles_comments = Comment.where(feedback: feedback) if feedback!="Any"
    article_ids = articles_comments.pluck(:article_id) if feedback!="Any"
    articles = articles.where(id: article_ids) if feedback!="Any"
    return articles
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all if params[:category].blank?
    @articles = Article.search_result(params[:category], params[:author], params[:title], params[:description], params[:feedback]) if params[:category].present? 
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :category, :description, :author)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)    
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commentor, :body, :feedback)
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def categories
    Article.pluck(:category).uniq rescue []
  end

  def authors
   return Article.pluck(:author).uniq rescue []
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :article_category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :article_description %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :article_author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<nav>
  
</nav>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-2" ></div>
  <div class="col-lg-8">
    <div class="ibox product-detail">
      <div class="ibox-content">
        <h2 class="font-bold m-b-xs"> ADVANCED SEARCH </h2>
        <br>
        <%= form_tag "articles", id: "form", method: :get do %>
        <div class="row">
          <div class="col-lg-3">
            <div class="form-group">
              <label>Category:</label>
              <%= select_tag "category", options_for_select(categories), class: 'form-control'%>
            </div>
          </div>
           <div class="col-lg-3">
            <div class="form-group">
              <label>Author:</label>
              <%= select_tag "author", options_for_select(authors), class: 'form-control'%>
            </div>
          </div>
          <div class="col-lg-3">
            <label>Title:</label>
            <input type="text" class="form-control" placeholder="Any" name="title" id="title">
          </div>  
        </div>
        <div class="row">
          <div class="col-lg-3">
            <div class="form-group">
              <label>Description:</label>
              <input type="text" class="form-control" placeholder="Any" name="description" id="min_sqr_ft_id"> 
            </div>
          </div>
          <div class="col-lg-3">
            <div class="form-group">
              <label>Feedback:</label>
              <%= select_tag "feedback", options_for_select(['Any','Good','Average','Poor']), class: 'form-control'%>
            </div>
          </div>
          <div class="col-lg-3" >
            <div class="form-group">
              <label></label>
              <input type="submit" class="form-control btn-danger" value="Search" id="btn_adv_search">
            </div>
          </div>
        </div>
        <!-- </form> -->
        <%end%>
      </div>
    </div>
 

    <br> 
    <%= link_to 'New Article', new_article_path %>
    <br>
    <% if @articles.blank?%>
    <div class="row">'
      <h2>Search criteria does not match</h2>
    </div>
    <% else %>
    <h1>Articles</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Description</th>
          <th>Author</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.category %></td>
            <td><%= link_to article.description, article %></td>
            <td><%= article.author %></td>
            <td></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
    <br>
   
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-lg-2" ></div>
  <div class="col-lg-8">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @article.title %>
	</p>

	<p>
	  <strong>Category:</strong>
	  <%= @article.category %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @article.description %>
	</p>

	<p>
	  <strong>Author:</strong>
	  <%= @article.author %>
	</p>

	<%= link_to 'Edit', edit_article_path(@article) %> |
	<%= link_to 'Back', articles_path %>


	<h2>Comments</h2>
	<% @article.comments.each do |comment| %>
	  <p>
	    <strong>Commenter:</strong>
	    <%= comment.commentor %>
	  </p>
	 
	  <p>
	    <strong>Body:</strong>
	    <%= comment.body %>
	  </p>
	  <p>
	    <strong>Feedback:</strong>
	    <%= comment.feedback %>
	  </p>
	   <%= link_to 'Destroy Comment', [comment.article, comment],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	<% end %>




	<h2>Add a comment:</h2>
	<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
	  <p>
	    <%= form.label :feedback %><br>
	    <%= form.select "feedback", options_for_select(['Good','Average','Poor']), class: 'form-control',id: :comment_feedback%>
	  </p>
	  <p>
	    <%= form.label :commenter %><br>
	    <%= form.text_field :commentor %>
	  </p>
	  <p>
	    <%= form.label :body %><br>
	    <%= form.text_area :body %>
	  </p>

	  <p>
	    <%= form.submit %>
	  </p>
	<% end %>
	</div>
	</div>
 

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :commentor %>
    <%= form.text_field :commentor, id: :comment_commentor %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= form.label :feedback %>
    <%= form.text_field :feedback, id: :comment_feedback %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id, id: :comment_article_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commentor</th>
      <th>Body</th>
      <th>Feedback</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commentor %></td>
        <td><%= comment.body %></td>
        <td><%= comment.feedback %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commentor:</strong>
  <%= @comment.commentor %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @comment.feedback %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
  $("#category").prepend('<option value="Category" selected>Any</option>');
  $("#author").prepend('<option value="Author" selected>Any</option>');

</script>